"""add_cv_photo_fks_to_student_company_hr_phone

Revision ID: 1cb69ad2fce5
Revises: 1c6c6a167a96
Create Date: 2026-05-14 09:22:23.879059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb69ad2fce5'
down_revision = '1c6c6a167a96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('photo_profile_id', sa.UUID(), nullable=True))
    op.alter_column('companies', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'companies', 'documents', ['photo_profile_id'], ['id'])
    op.add_column('hrs', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('cv_id', sa.UUID(), nullable=True))
    op.add_column('students', sa.Column('photo_profile_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'students', 'documents', ['cv_id'], ['id'])
    op.create_foreign_key(None, 'students', 'documents', ['photo_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'photo_profile_id')
    op.drop_column('students', 'cv_id')
    op.drop_column('hrs', 'phone_number')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.alter_column('companies', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('companies', 'photo_profile_id')
    # ### end Alembic commands ###
