"""Refactor to User + Profile pattern

Revision ID: ad213f3e577e
Revises: bb3ee713ba5d
Create Date: 2026-02-08 22:25:06.151541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad213f3e577e'
down_revision = 'bb3ee713ba5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: Create new profile tables
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_address', sa.String(), nullable=False),
    sa.Column('company_phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_nim'), 'students', ['nim'], unique=True)
    
    # Step 2: Migrate existing data from users table to profile tables
    # Get database connection
    connection = op.get_bind()
    
    # Migrate students
    connection.execute(sa.text("""
        INSERT INTO students (user_id, nim, major, created_at)
        SELECT id, nim, major, created_at
        FROM users
        WHERE role = 'STUDENT' AND nim IS NOT NULL AND major IS NOT NULL
    """))
    
    # Migrate companies
    connection.execute(sa.text("""
        INSERT INTO companies (user_id, company_name, company_address, company_phone, created_at)
        SELECT id, company_name, company_address, company_phone, created_at
        FROM users
        WHERE role = 'COMPANY' AND company_name IS NOT NULL
    """))
    
    # Migrate admins
    connection.execute(sa.text("""
        INSERT INTO admins (user_id, created_at)
        SELECT id, created_at
        FROM users
        WHERE role = 'ADMIN'
    """))
    
    # Step 3: Drop old columns from users table
    op.drop_constraint('users_nim_key', 'users', type_='unique')
    op.drop_column('users', 'nim')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'major')
    op.drop_column('users', 'company_phone')
    op.drop_column('users', 'company_address')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('company_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nim', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_nim_key', 'users', ['nim'])
    op.drop_index(op.f('ix_students_nim'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
