"""add_offers_table

Revision ID: ae99694aed13
Revises: b5197371165e
Create Date: 2026-05-15 10:28:42.294884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae99694aed13'
down_revision = 'b5197371165e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('offer_detail', sa.Text(), nullable=True),
    sa.Column('compensation', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('offering_file_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['offering_file_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_application_id'), 'offers', ['application_id'], unique=True)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_application_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
